### ISSUE TITLE
Network Setup

### ISSUE THREAD

**Issue by coolpalani** [fortinet-solutions-cse/mirantis_testbed#1]
Hello,

I followed your instructions for deploy Mirantis OpenStack9.0 fuel master node and slave nodes as well.
After fuel master completed, I logged the FUEL UI and created environment for deploy OpenStack.
I am facing some issue in network connectivity.
Could you guide me how are you configuring network in UI before initiate deployment

**Comment by mamunozgonzalez** [comment]
Hi coolpalani,
 sure, but take into account that what you downloaded is not complete yet. You only got a basic skeleton for creating every VM needed to run MOS9.2 + Contrail.

Regarding your connectivity issue:
 - Are you using the network connectivity test link that is available in Fuel UI?
 - Have you checked that your networks have been deployed correctly? (are they available in Fuel cli?)
 - Once you have controller + computes deployed... have you entered each node's configuration to allocate each interface to each network from Fuel UI?
 - Have you disabled VLAN tagging?
 - Also please, copy and paste your network configuration from Fuel UI here.

BR.
MA.

**Comment by coolpalani** [comment]
Hello Mamunozgonzalez,

>> Are you using the network connectivity test link that is available in Fuel UI?
Yes, I am using Mirantis Fuel UI to test connectivity

>> Have you checked that your networks have been deployed correctly? (are they available in Fuel cli?)

which command should i want use to fetch the details

https://docs.openstack.org/fuel-docs/latest/userdocs/fuel-user-guide/cli/cli_comparison_matrix.html#cli-comparison-matrix
>> Once you have controller + computes deployed... have you entered each node's configuration to allocate each interface to each network from Fuel UI?

once nodes are bootstrap, it's automatically detected and shown in UI. I didn't feed the details as manually. but in network tap shown as default network info instead of fetch from each node.
I reedited admin,public,private,storage and management ip address details.

>> Have you disabled VLAN tagging?
I disabled but didn't help

>> Also please, copy and paste your network configuration from Fuel UI here.
I will attach snapshots anon.
